import React, { useState } from 'react';
import { Sparkles, Shield, AlertCircle, CheckCircle2, Lightbulb, Send, RefreshCw, TrendingDown } from 'lucide-react';
import { Category, Transaction, Debt, AppSettings, AIInsight } from '../../types/finance';
import { generateMockInsight, mockBudgetAnswer } from '../../lib/ai';
import { saveSettings } from '../../lib/storage';

interface Props {
  categories: Category[];
  transactions: Transaction[];
  debts: Debt[];
  settings: AppSettings;
  insight: AIInsight | null;
  onInsightGenerated: (insight: AIInsight) => void;
  onSettingsChange: (s: AppSettings) => void;
}

export default function AICoach({ categories, transactions, debts, settings, insight, onInsightGenerated, onSettingsChange }: Props) {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [generating, setGenerating] = useState(false);
  const [answering, setAnswering] = useState(false);

  function acknowledgePrivacy() {
    const updated = { ...settings, aiPrivacyAcknowledged: true };
    onSettingsChange(updated);
    saveSettings(updated);
  }

  async function handleGenerate() {
    setGenerating(true);
    await new Promise((r) => setTimeout(r, 1200));
    const result = generateMockInsight(categories, transactions, debts, settings);
    onInsightGenerated(result);
    setGenerating(false);
  }

  async function handleAsk(e: React.FormEvent) {
    e.preventDefault();
    if (!question.trim()) return;
    setAnswering(true);
    await new Promise((r) => setTimeout(r, 700));
    const resp = mockBudgetAnswer(question, categories, transactions, debts, settings);
    setAnswer(resp);
    setAnswering(false);
  }

  if (!settings.aiPrivacyAcknowledged) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="font-heading font-bold text-2xl text-gray-900">AI Coach</h1>
          <p className="text-gray-500 text-sm mt-1">Personalized, shame-free financial guidance.</p>
        </div>
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 max-w-lg mx-auto text-center">
          <div className="w-14 h-14 rounded-2xl bg-violet-100 flex items-center justify-center mx-auto mb-4">
            <Shield size={24} className="text-violet-600" />
          </div>
          <h2 className="font-heading font-bold text-xl text-gray-900 mb-3">Privacy & Disclaimer</h2>
          <div className="text-sm text-gray-600 space-y-3 text-left mb-6">
            <p>Your financial data stays on your device. The AI Coach analyzes your local budget data to generate insights — nothing is sent to a server.</p>
            <p>For the MVP, all insights are generated by a smart local algorithm, not an external AI. Future versions may offer optional cloud AI integration.</p>
            <div className="flex gap-2 p-3 bg-amber-50 rounded-xl border border-amber-200">
              <AlertCircle size={16} className="text-amber-600 shrink-0 mt-0.5" />
              <p className="text-amber-800">This app provides educational budgeting guidance, not professional financial advice. Always consult a qualified advisor for major financial decisions.</p>
            </div>
          </div>
          <button
            onClick={acknowledgePrivacy}
            className="w-full py-3 bg-violet-600 text-white font-medium rounded-xl hover:bg-violet-700 transition-colors"
          >
            I understand — let's go
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="font-heading font-bold text-2xl text-gray-900">AI Coach</h1>
          <p className="text-gray-500 text-sm mt-1">Your personalized financial action plan.</p>
        </div>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="flex items-center gap-2 px-4 py-2.5 bg-violet-600 text-white text-sm font-medium rounded-xl hover:bg-violet-700 transition-colors disabled:opacity-60"
        >
          {generating ? <RefreshCw size={16} className="animate-spin" /> : <Sparkles size={16} />}
          {generating ? 'Analyzing...' : insight ? 'Regenerate Plan' : 'Generate Weekly Plan'}
        </button>
      </div>

      {!insight && !generating && (
        <div className="bg-gradient-to-br from-violet-50 to-violet-100 border border-violet-200 rounded-2xl p-8 text-center">
          <div className="w-16 h-16 rounded-2xl bg-violet-200 flex items-center justify-center mx-auto mb-4">
            <TrendingDown size={28} className="text-violet-700" />
          </div>
          <h2 className="font-heading font-bold text-xl text-violet-900 mb-2">Ready to coach you</h2>
          <p className="text-violet-700 text-sm max-w-sm mx-auto">
            Click "Generate Weekly Plan" to get a personalized budget analysis, debt advice, and actionable next steps.
          </p>
        </div>
      )}

      {generating && (
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 text-center">
          <div className="w-12 h-12 rounded-2xl bg-violet-100 flex items-center justify-center mx-auto mb-4">
            <Sparkles size={22} className="text-violet-600 animate-pulse" />
          </div>
          <p className="text-gray-700 font-medium">Analyzing your finances...</p>
          <p className="text-gray-400 text-sm mt-1">Reviewing budget, debts, and spending patterns.</p>
        </div>
      )}

      {insight && !generating && (
        <>
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
            <div className="flex items-center gap-2 mb-3">
              <Sparkles size={16} className="text-violet-600" />
              <h2 className="font-heading font-semibold text-gray-900">Weekly Summary</h2>
              <span className="ml-auto text-xs text-gray-400">
                {new Date(insight.generatedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}
              </span>
            </div>
            <p className="text-sm text-gray-700 leading-relaxed">{insight.summary}</p>
          </div>

          {insight.alerts.length > 0 && (
            <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
              <div className="flex items-center gap-2 mb-3">
                <AlertCircle size={16} className="text-amber-500" />
                <h2 className="font-heading font-semibold text-gray-900">Alerts</h2>
              </div>
              <div className="space-y-2">
                {insight.alerts.map((a, i) => (
                  <div key={i} className="flex items-start gap-2.5 p-3 bg-amber-50 rounded-xl border border-amber-100">
                    <AlertCircle size={14} className="text-amber-500 mt-0.5 shrink-0" />
                    <p className="text-sm text-amber-800">{a}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
            <div className="flex items-center gap-2 mb-3">
              <CheckCircle2 size={16} className="text-teal-600" />
              <h2 className="font-heading font-semibold text-gray-900">Recommended Actions</h2>
            </div>
            <div className="space-y-2.5">
              {insight.actions.map((a, i) => (
                <div key={i} className="flex items-start gap-3">
                  <div className="w-6 h-6 rounded-full bg-teal-100 text-teal-700 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">{i + 1}</div>
                  <p className="text-sm text-gray-700 leading-relaxed">{a}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
            <div className="flex items-center gap-2 mb-3">
              <TrendingDown size={16} className="text-blue-600" />
              <h2 className="font-heading font-semibold text-gray-900">Debt Strategy</h2>
            </div>
            <p className="text-sm text-gray-700 leading-relaxed">{insight.debtAdvice}</p>
          </div>

          {insight.savingsOpportunities.length > 0 && (
            <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
              <div className="flex items-center gap-2 mb-3">
                <Lightbulb size={16} className="text-green-600" />
                <h2 className="font-heading font-semibold text-gray-900">Savings Opportunities</h2>
              </div>
              <div className="space-y-2">
                {insight.savingsOpportunities.map((o, i) => (
                  <div key={i} className="flex items-start gap-2.5 p-3 bg-green-50 rounded-xl border border-green-100">
                    <Lightbulb size={14} className="text-green-600 mt-0.5 shrink-0" />
                    <p className="text-sm text-green-800">{o}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </>
      )}

      {/* Ask my budget */}
      <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
        <div className="flex items-center gap-2 mb-4">
          <div className="w-7 h-7 rounded-lg bg-violet-100 flex items-center justify-center">
            <Sparkles size={14} className="text-violet-600" />
          </div>
          <h2 className="font-heading font-semibold text-gray-900">Ask My Budget</h2>
        </div>
        <form onSubmit={handleAsk} className="flex gap-2">
          <input
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="e.g. How much did I spend on dining?"
            className="flex-1 px-3.5 py-2.5 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-violet-500 focus:border-transparent"
          />
          <button
            type="submit"
            disabled={answering || !question.trim()}
            className="px-4 py-2.5 bg-violet-600 text-white rounded-xl hover:bg-violet-700 transition-colors disabled:opacity-60"
          >
            {answering ? <RefreshCw size={16} className="animate-spin" /> : <Send size={16} />}
          </button>
        </form>
        {answer && (
          <div className="mt-3 p-4 bg-violet-50 rounded-xl border border-violet-100">
            <p className="text-sm text-violet-900 leading-relaxed">{answer}</p>
          </div>
        )}
        <p className="text-xs text-gray-400 mt-3">
          Responses are generated from your local data. This is educational guidance, not professional advice.
        </p>
      </div>
    </div>
  );
}
